services:
  postgres:
    image: postgres:16-alpine
    container_name: pipeline_postgres
    environment:
      POSTGRES_DB: taxi_data
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipeline_user -d taxi_data"]
      interval: 5s
      timeout: 5s
      retries: 5

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipeline_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      USE_POSTGRES: "true"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: taxi_data
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
    volumes:
      - ./src/data/raw:/app/src/data/raw
    command: python src/main.py

volumes:
  postgres_data:

